spring:
  servlet:
    multipart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false #不设置这个jpa保存会报错
    #show-sql: true
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/assets?serverTimezone=UTC
    username: root
    password: root
    #连接池配置
    dbcp2: 
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
server:
  port: 8083
  servlet:
    context-path: /soup
#log
logging: 
  level:
    org:
      hibernate:
        SQL: DEBUG  
